[main]
font=JetBrains Mono Nerd Font:size=9
letter-spacing=0

[scrollback]
# lines=1000
# multiplier=2.0
# indicator-position=relative
# indicator-format=""

[cursor]
style=beam
beam-thickness=1

[main]
font=JetBrainsMono Nerd Font:size=11
pad=10x10

[colors-dark]
alpha=0.5
