# Cores (usando o formato 0x ARGB ou RRGGBB)
accent = 0xFF8839EF
text = 0xFFCAD3F5
background = 0xFF24273A

# Fontes e Tamanhos
font_family = "JetBrains Mono Nerd Font"
font_size = 12
h1_size = 20

# Aparência
rounding_large = 12
rounding_small = 6
