$terminal    = alacritty
$fileManager = thunar
$browser     = zen-browser
$launcher    = hyprlauncher
$editor 	 = zeditor

exec-once = waybar
exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprctl setcursor Qogir-white-cursors 21

env = XCURSOR_THEME, Qogir-white-cursors
env = XCURSOR_SIZE, 21
