windowrule = suppress_event maximize, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
windowrule = float on,                                    match:class SoundWireServer
windowrule = workspace special:magic silent,              match:class ^(SoundWireServer)$
windowrule = workspace 2,                                 match:class $browser
windowrule = workspace 3,                                 match:class VSCodium
windowrule = float on,                                    match:class org.pulseaudio.pavucontrol
windowrule = float on,                                    match:class nm-connection-editor
windowrule = float on,                                    match:class discord
windowrule = float on,                                    match:class org.gnome.Nautilus
windowrule = float on, size (monitor_w*0.8) (monitor_h*0.8), opacity 1.0 1.0 1.0, match:title (System Monitor)
windowrule = workspace special:magic silent,              match:class ^(Spotify)$
