Net/ThemeName "Reversal-Dark"
Net/IconThemeName "yet-another-monochrome-icon-set"
Gtk/CursorThemeName "Qogir-white-cursors"
Net/EnableEventSounds 1
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
